entando/entando-components

plugins/entando-plugin-jpfileattribute/src/main/java/org/entando/entando/plugins/jpfileattribute/aps/system/entity/model/FileAttribute.java
plugins/entando-plugin-jpfileattribute/src/main/java/org/entando/entando/plugins/jpfileattribute/aps/system/entity/model/JAXBFileAttribute.java
plugins/entando-plugin-jpfileattribute/src/main/java/org/entando/entando/plugins/jpfileattribute/aps/system/file/AttachedFile.java
plugins/entando-plugin-jpgeoref/src/main/java/com/agiletec/plugins/jpgeoref/aps/system/services/content/model/extraAttribute/CoordsAttribute.java

This pull request complete the issue "JSON Unmarshal" on entando-core project

Jaxb improvement

---

plugins/entando-plugin-jpldap/src/main/java/com/agiletec/plugins/jpldap/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpldap/src/main/java/com/agiletec/plugins/jpldap/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpldap/src/main/java/com/agiletec/plugins/jpldap/apsadmin/ldapAdmin.xml
plugins/entando-plugin-jpldap/src/main/resources/entando-struts-plugin.xml
plugins/entando-plugin-jpldap/src/main/resources/spring/plugins/jpldap/apsadmin/jpldapActionsConfig.xml
plugins/entando-plugin-jpldap/src/main/webapp/WEB-INF/plugins/jpldap/apsadmin/jpldap-tiles.xml
plugins/entando-plugin-jpldap/src/main/webapp/WEB-INF/plugins/jpldap/apsadmin/jsp/common/layouts/subMenu.jsp
plugins/entando-plugin-jpldap/src/main/webapp/WEB-INF/plugins/jpldap/apsadmin/jsp/user/ldapConfig.jsp
plugins/entando-plugin-jpuserreg/src/main/webapp/WEB-INF/plugins/jpuserreg/apsadmin/jsp/config/config-entry.jsp

ENQT-127: Integration - UX Components - LDAP - Create LDAP Page

---

plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/common/template/subMenu.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/notifier/config.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/notifier/configSavedConfirm.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/workflow/entryRole.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/workflow/entrySteps.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/webapp/WEB-INF/plugins/jpcontentworkflow/apsadmin/jsp/workflow/workflowList.jsp
plugins/entando-plugin-jpuserreg/src/main/webapp/WEB-INF/plugins/jpuserreg/apsadmin/jsp/common/layouts/subMenu.jsp

ENQT-136: Integration - UX Components - Content Workflow - Create Content Workflow Page

---

plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/comment/package_en.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/comment/package_it.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/config/package_en.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/config/package_it.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/idea/package_en.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/idea/package_it.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/ideainstance/package_en.properties
plugins/entando-plugin-jpcollaboration/src/main/java/com/agiletec/plugins/jpcrowdsourcing/apsadmin/ideainstance/package_it.properties
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/category/categoryReferences-jack.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/comment/comment-delete.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/comment/comment-list.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/comment/comment-view.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/common/layouts/subMenu.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/config/configSaved.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/config/entryConfig.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/idea/idea-delete-ref.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/idea/idea-delete.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/idea/idea-entry.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/idea/idea-list.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/ideainstance/ideaInstance-entry.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/ideainstance/ideaInstance-trash.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/ideainstance/ideaInstance_list.jsp
plugins/entando-plugin-jpcollaboration/src/main/webapp/WEB-INF/plugins/jpcollaboration/apsadmin/jsp/portal/specialwidget/ideainstance/config_ideaInstance.jsp
plugins/pom.xml

ENQT-138-social-collaboration

---

apps/pom.xml
plugins/pom.xml
ui-bundles/pom.xml

Enqt 204 - get page

---

plugins/entando-plugin-jpnewsletter/src/main/java/com/agiletec/plugins/jpnewsletter/aps/system/services/newsletter/NewsletterManager.java
plugins/entando-plugin-jpnewsletter/src/main/java/com/agiletec/plugins/jpnewsletter/apsadmin/config/NewsletterConfigAction.java
plugins/entando-plugin-jpnewsletter/src/main/webapp/WEB-INF/plugins/jpnewsletter/apsadmin/jsp/common/template/subMenu.jsp

amend newletter FE and getPage

ENQT-368 Newsletter - amend FE

---

plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/message/package_it.properties
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/config/entryMessageType.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/config/messageTypeSummary.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/entity-message-list.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/entryAnswer.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/messageFinding.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/trashMessage.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jsp/message/viewMessage.jsp

webdynamicform

---

plugins/entando-plugin-jpactionlogger/src/main/webapp/WEB-INF/plugins/jpactionlogger/apsadmin/jsp/common/template/subMenu.jsp

check jpactionlogger

---

plugins/entando-plugin-jpwidgetutils/src/main/java/org/entando/entando/plugins/jpwidgetutils/aps/tags/WidgetReplicatorTag.java
plugins/entando-plugin-jpwidgetutils/src/main/java/org/entando/entando/plugins/jpwidgetutils/apsadmin/portal/specialwidget/replicator/ReplicatorWidgetAction.java
plugins/entando-plugin-jpwidgetutils/src/main/resources/spring/plugins/jpwidgetutils/apsadmin/portal/specialWidgetActionsConfig.xml

ENQT-378 - Widget utils

---

plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/common/template/extraresources/facet.jsp
plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/facetnav-result-entry.jsp
plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/facetnav-tree-entry.jsp
plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/include/content-type-list.jsp
plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/include/facet-list.jsp

facet tree, search result, extra resources

Update jpfacetnav  specialWidgets

---

plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/include/content-type-list.jsp

Tag icon removed from selected content type list.

update Facet Navigation

---

plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/config/CalendarConfigAction.java
plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/config/package_en.properties
plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/config/package_it.properties
plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/global-messages_it.properties
ui-bundles/app-views/entando-app-view-calendar-default/README.md
ui-bundles/app-views/entando-app-view-calendar-default/src/main/resources/sql/bundles/entando-app-view-calendar-default/port_data_production.sql

* fix class java class
* fix port_data_production.sql
* add README.md

ENQT-381 calendar

---

plugins/entando-plugin-jpcalendar/README.md

Add README.md

---

plugins/entando-plugin-jpactionlogger/src/main/webapp/WEB-INF/plugins/jpactionlogger/apsadmin/jsp/common/template/subMenu.jsp

add css class

---

plugins/entando-plugin-jpavatar/src/main/java/org/entando/entando/plugins/jpavatar/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpavatar/src/main/java/org/entando/entando/plugins/jpavatar/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpavatar/src/main/webapp/WEB-INF/plugins/jpavatar/apsadmin/jsp/avatar/avatar-delete-confirm.jsp
plugins/entando-plugin-jpavatar/src/main/webapp/WEB-INF/plugins/jpavatar/apsadmin/jsp/avatar/avatar-entry.jsp
plugins/entando-plugin-jpavatar/src/main/webapp/WEB-INF/plugins/jpavatar/apsadmin/jsp/avatar/avatar-settings.jsp
plugins/entando-plugin-jpavatar/src/main/webapp/WEB-INF/plugins/jpavatar/apsadmin/jsp/config/jpavatar_config.jsp

Avatar fixed label and structure

---

plugins/entando-plugin-jprss/src/main/java/org/entando/entando/plugins/jprss/apsadmin/config/package_en.properties
plugins/entando-plugin-jprss/src/main/java/org/entando/entando/plugins/jprss/apsadmin/config/package_it.properties
plugins/entando-plugin-jprss/src/main/webapp/WEB-INF/plugins/jprss/apsadmin/jsp/channelsList.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/aps/system/services/message/MessageManager.java
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/message/package_en.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/message/package_it.properties
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jpwebdynamicform-tiles.xml

fix usses report by Roberta for Web Dynamic Form

ENQT-411 Web Dynamic Form

---

plugins/entando-plugin-jpcalendar/src/main/webapp/WEB-INF/plugins/jpcalendar/apsadmin/jsp/config/calendar-config-entry.jsp
plugins/entando-plugin-jpcontentworkflow/src/main/java/com/agiletec/plugins/jpcontentworkflow/apsadmin/notifier/package_it.properties
plugins/entando-plugin-jpgeoref/README.md
plugins/entando-plugin-jpwidgetutils/README.md

add README.md jpgeoref, jpwidgetutils

Release 4.3 readmes

---

plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/aps/system/services/userreg/model/IUserRegConfig.java
plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/aps/system/services/userreg/model/UserRegConfig.java
plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/apsadmin/config/UserRegConfigAction-validation.xml
plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/apsadmin/config/UserRegConfigAction.java
plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/apsadmin/config/package_en.properties
plugins/entando-plugin-jpuserreg/src/main/java/com/agiletec/plugins/jpuserreg/apsadmin/config/package_it.properties
plugins/entando-plugin-jpuserreg/src/main/webapp/WEB-INF/plugins/jpuserreg/apsadmin/jsp/config/config-entry.jsp
plugins/entando-plugin-jpuserreg/src/main/webapp/WEB-INF/plugins/jpuserreg/apsadmin/jsp/config/config-saved.jsp
plugins/entando-plugin-jpuserreg/src/main/webapp/WEB-INF/plugins/jpuserreg/apsadmin/jsp/config/inc/form-errors.jsp

Jsp template, emailSenderCode validation, labels

Bug fix jpuserreg

---

plugins/entando-plugin-jpnewsletter/src/main/webapp/WEB-INF/plugins/jpnewsletter/apsadmin/jsp/newsletter/content-detail.jsp
plugins/entando-plugin-jpnewsletter/src/main/webapp/WEB-INF/plugins/jpnewsletter/apsadmin/jsp/newsletter/include/content-detail.jsp

Fix jpnewsletter

---

plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/config/package_en.properties
plugins/entando-plugin-jpcalendar/src/main/java/org/entando/entando/plugins/jpcalendar/apsadmin/config/package_it.properties
plugins/entando-plugin-jpcalendar/src/main/webapp/WEB-INF/plugins/jpcalendar/apsadmin/jsp/config/calendar-config-entry.jsp
plugins/entando-plugin-jprssaggregator/src/main/webapp/WEB-INF/plugins/jprssaggregator/apsadmin/jprssaggregator-tiles.xml
plugins/entando-plugin-jprssaggregator/src/main/webapp/WEB-INF/plugins/jprssaggregator/apsadmin/jsp/aggregator/confirmRemove.jsp
plugins/entando-plugin-jprssaggregator/src/main/webapp/WEB-INF/plugins/jprssaggregator/apsadmin/jsp/aggregator/entryItem.jsp
plugins/entando-plugin-jprssaggregator/src/main/webapp/WEB-INF/plugins/jprssaggregator/apsadmin/jsp/aggregator/list.jsp
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/message/config/package_en.properties
plugins/entando-plugin-jpwebdynamicform/src/main/java/com/agiletec/plugins/jpwebdynamicform/apsadmin/message/config/package_it.properties
plugins/entando-plugin-jpwebdynamicform/src/main/webapp/WEB-INF/plugins/jpwebdynamicform/apsadmin/jpwebdynamicform-tiles.xml
plugins/entando-plugin-jpwebform/src/main/java/org/entando/entando/plugins/jpwebform/apsadmin/message/config/package_en.properties
plugins/entando-plugin-jpwebform/src/main/java/org/entando/entando/plugins/jpwebform/apsadmin/message/config/package_it.properties

* fix label calendar, rssagregator, webform

Release 4.3      fix label calendar, rssagregator, webform

---

plugins/entando-plugin-jpfacetnav/src/main/java/com/agiletec/plugins/jpfacetnav/apsadmin/portal/specialwidget/package_en.properties
plugins/entando-plugin-jpfacetnav/src/main/java/com/agiletec/plugins/jpfacetnav/apsadmin/portal/specialwidget/package_it.properties
plugins/entando-plugin-jpfacetnav/src/main/webapp/WEB-INF/plugins/jpfacetnav/apsadmin/jsp/portal/specialwidget/include/facet-list.jsp

fix jpfacetnav

---

plugins/entando-plugin-jpcalendar/src/main/webapp/WEB-INF/plugins/jpcalendar/apsadmin/jsp/config/calendar-config-entry.jsp
plugins/entando-plugin-jpcontentscheduler/src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/config/package_en.properties
plugins/entando-plugin-jpcontentscheduler/src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/config/package_it.properties
plugins/entando-plugin-jpcontentscheduler/src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpcontentscheduler/src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/global-messages_it.properties

Release 4.3: fix label jpcontentscheduler

---

plugins/entando-plugin-jpaddressbook/src/main/java/com/agiletec/plugins/jpaddressbook/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpaddressbook/src/main/java/com/agiletec/plugins/jpaddressbook/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/addressBook/contactFinding.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/addressBook/entryContact.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/addressBook/trashContact.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/addressBook/viewContact.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/common/template/breadcrumb.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/common/template/subMenu.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/common/template/tabMenu.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/vcard/configFields.jsp
plugins/entando-plugin-jpaddressbook/src/main/webapp/WEB-INF/plugins/jpaddressbook/apsadmin/jsp/vcard/entryConfig.jsp

fix layout AddressBook

---

.gitignore
plugins/entando-plugin-jpkiebpm/README.md
plugins/entando-plugin-jpkiebpm/pom.xml
pom.xml

Forced inclusion of TXT files inside the generated JAR

---

plugins/entando-plugin-jprestapi/src/main/java/org/entando/entando/plugins/jprestapi/aps/core/RequestBuilder.java

Fixed bug when no payload is returned by the server

jprestapi: fixed bug when no payload is returned by the server

---

plugins/entando-plugin-jpkiebpm/src/main/db/update/scriptPort.sql

add script for update widget tasklist and processlist

add scriptPort.sql

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/KieBpmSystemConstants.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/IKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieEndpointDictionary.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/FSIDemoHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/JsonHelper.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/FsiMortgageDemoTest.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/TestFSIDemoHelper.java

Refactored submitHumanFormTask(... Map queryStringParams, Map input)
Added getHumanTaskListForAdmin(user, ...) and getHumanTaskListForUser(user, ...)
Test aligned

Task lists

---

plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/custom-data-table.js

add behavior createdrow

---

plugins/entando-plugin-jpkiebpm/README.md
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/KieBpmConfig.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/config/KieBpmConfigAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/config/kieBpmConfig.xml
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/config/package_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/config/config-entry.jsp

Added test button and debug switch

jpkiebpm: added debug swich and test button on configuration entry

---

ui-bundles/misc/entando-misc-bootstrap/src/main/webapp/resources/static/entando-misc-bootstrap/bootstrap/package.json

Update version to resolve security issues:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-8857
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-8858

Update uglify version for CVE-2015-8857 CVE-2015-8858

---

plugins/entando-plugin-jpkiebpm/app-builder/src/ui/server-config/common/ServerConfigForm.js
plugins/entando-plugin-jpkiebpm/app-builder/src/ui/widgets/BpmCaseInstanceFormContainer.js
plugins/entando-plugin-jpkiebpm/app-builder/src/ui/widgets/BpmChannelForm.js

- Fix not required field
- Fix not-wrapped redux forms

En 1315 fix webapp name not required

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/EnvironmentBasedConfigHelper.java
plugins/entando-plugin-jpkiebpm/src/main/resources/sql/plugins/jpkiebpm/port_data_production.sql
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/TestKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/test/resources/sql/plugins/jpkiebpm/port_data_test.sql

EN-1666 has already been merged successfully into v5.0.1-dev. This PR will ensure the changes are in MASTER too.

EN-1666 Repeating the changes on MASTER

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/extraAttribute/LinkAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/extraAttribute/LinkAttributeHandler.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/contentAttribute.xml
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/ContentLinkAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/LinkAttributeAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/PageLinkAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/UrlLinkAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/helper/ILinkAttributeActionHelper.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/link/helper/LinkAttributeActionHelper.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ExtendedResourceFinderAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/package_en.properties
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/package_it.properties
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/entando-link-attributes.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/entando-link.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/info-prev-value.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-1.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-2.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-3.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/type-5.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/link-attributes-autocomplete.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configContentLinkType.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configPageLinkType.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/configUrlLinkType.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/linkAttribute/linkAttributeConfigIntro.jsp
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestContentManager.java

Hi @joewhite101 , @eugeniosant ,
Additional link attributes added.
Thanks!

En-1608-seo-add-attributes-to-a-link-type

---

pom.xml

Add plugin to upload sources jars to maven

Add maven-source-plugin

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/IntroNewContentAction.java

Default date set to current date for new contents added.
Thanks!

EN-1852-set-default-date-to-current-date

---

plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/AllTests.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/apsadmin/content/AbstractTestContentAttribute.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/apsadmin/content/TestContentPreviewAction.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/apsadmin/content/TestSaveBooleanAttributes.java
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/form/form_type_view.jsp

Create a new PR to see if jenkins will update.

Hotfix jboss v5.0.1 dev

---

plugins/entando-plugin-jacms/pom.xml
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractMultiInstanceResource.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/BaseResourceDataBean.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceDataBean.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceInterface.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceDOM.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceHandler.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_en.properties
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_it.properties
plugins/entando-plugin-jacms/src/main/resources/spring/plugins/jacms/aps/managers/resourceTypesDef.xml
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManagerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/mock/MockResourceDataBean.java
plugins/entando-plugin-jpversioning/src/test/java/com/agiletec/plugins/jpversioning/aps/system/services/resource/MockResourceDataBean.java
plugins/src/test/config/conf/systemParams.properties

Resource metadata added to the CMS plugin.
It should be merged a the same time with the entando-components and entando-archetypes PR below:
entando/entando-core#568
https://github.com/entando/entando-archetypes/pull/66
Thanks!

EN-1857-read-and-save-metadata-on-images-in-multiple-uploader

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_en.properties
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/package_it.properties
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/fileUploadAddFields.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/fileUploadFieldLabelI18n.jsp

File buttons i18n added.
It should be merged a the same time with the entando-core PR below:
https://github.com/entando/entando-core/pull/571
Thanks!

EN-1875-CMS-contents-labels-translations 

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/apsadmin/resource/TestMultipleResourceAction.java

Saving metadata when updating an existing resource fixed.
Thanks!

EN-1913-digital-assets-update-without-file-delete-saved-metadata

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceDOM.java

Hi @joewhite101 @eugeniosant ,
Null metadata value check added.
Could you please take a look at this PR?
Thanks!

EN-1914-Digital-Assets-Impossible-to-add-file-with-null-value-metadata

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/parse/ResourceDOM.java

metadata with special character fix added.
Could you please review this PR?
thanks!

EN-1918-special-characters-metadata

---

plugins/src/test/config/conf/contextTestParams.properties
pom.xml

Added profile to speedup normal development process

Sonar profile en 1964

---

plugins/entando-plugin-jacms/src/main/resources/sql/plugins/jacms/port_data_production.sql

labels added.
Could you please have look?
Thanks!

EN-1923-not-correct-labels-in-contents-preview

---

plugins/entando-plugin-jpwebdynamicform/src/main/resources/sql/plugins/jpwebdynamicform/serv_data_production.sql

EN-1720 Changed permission description from Italian to English

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/KieBpmSystemConstants.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/IKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieEndpointDictionary.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/CaseProgressWidgetHelpers.java

this is the cherry-pick from [this PR](https://github.com/entando/entando-components/pull/388) 
Thanks!

[5.0.1] EN-2207-501-Fix-pam-process-diagram-widget

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IndexerDAO.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearcherDAO.java

Depends on the merging of this PR in core:
https://github.com/entando/entando-core/pull/734

Update lucene version

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmCaseProgressAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/CaseProgressWidgetHelpers.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmCaseProgressWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/package_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/package_it.properties
plugins/entando-plugin-jpkiebpm/src/main/resources/sql/plugins/jpkiebpm/port_data_production.sql
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-case-progress-status.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-process-diagram.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-actions.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-chart.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-comments.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-details.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-file.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-instance-selector.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-progress-status.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-roles.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-process-diagram.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/portal/specialwidget/bpmCaseProgressConfig.jsp
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/AllTests.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/TestCaseProgressWidgetHelpers.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/TestDataUXBuilder.java
plugins/entando-plugin-jpkiebpm/src/test/resources/examples/json/milestones.json

Hey @joewhite101,
progress status widget refactoring and tests added.
Thanks!

[5.0.2] EN-2225-502-drag-and-drop-case-progress-status

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/KieBpmSystemConstants.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/IKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieEndpointDictionary.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/CaseProgressWidgetHelpers.java

Widget fixed, now the graph is showed as expected.
Thanks!

 EN-2207-Fix-pam-process-diagram-widget

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/FormToBpmHelper.java

Hey @joewhite101 ,
this is the fix for the checkbox with null value. 
Now if a checkbox is not checked, the value is set to false and  added to the posted json.
Thanks!

[5.0.3] EN-1981-503-Fix-checkbox-round-tripping-in-PAM-forms

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/IKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-process-diagram.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-actions.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-chart.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-comments.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-details.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-file.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-instance-selector.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-progress-status.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-roles.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-process-diagram.jsp

This is the data table task list show diagram fix.
Thanks!

[5.0.3] EN-2264-503-PAM-widgets-data-table-task-list-show-diagram-fix

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmCaseProgressAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/CaseProgressWidgetHelpers.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmCaseProgressWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/package_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/package_it.properties
plugins/entando-plugin-jpkiebpm/src/main/resources/sql/plugins/jpkiebpm/port_data_production.sql
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-case-progress-status.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-process-diagram.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-actions.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-chart.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-comments.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-details.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-file.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-instance-selector.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-roles.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-process-diagram.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/portal/specialwidget/bpmCaseProgressConfig.jsp
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/AllTests.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/TestCaseProgressWidgetHelpers.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/TestDataUXBuilder.java
plugins/entando-plugin-jpkiebpm/src/test/resources/examples/json/milestones.json

this is the cherry-pick from [this PR](https://github.com/entando/entando-components/pull/401).
Thanks!

[5.0.3] EN-2225-503-drag-and-drop-case-progress-status

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/init/servdb/KieFormOverride.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormOverrideDAO.java

EN-2205 (5.0.3) Used int instead of boolean for RDBMS compatibility

---

plugins/src/test/config/conf/systemParams.properties

Implemented refresh token flow

EN-2273 Complete OAuth2 flow

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/IKieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-actions.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-chart.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-comments.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-details.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-file.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-instance-selector.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-case-roles.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp

this is the cherry-pick from [this PR](https://github.com/entando/entando-components/pull/415).
Could you please take a look?
Thanks!

EN-2264-PAM-widgets-data-table-task-list-show-diagram-fix

---

plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/config/config-kie-server-list.jsp

this is the cherry-pick from the commit of [this PR](https://github.com/entando/entando-components/pull/429).
Thanks!

EN-2294-PAM-config-remove-logs-after-click-on-test-all

---

ui-bundles/themes/entando-page-inspinia_BPM/src/main/resources/sql/bundles/entando-page-inspinia_BPM/port_data_production.sql

Hi @joewhite101 @DMinnai ,
this is the cherry-pick from [this master commit](https://github.com/entando/entando-components/pull/432/commits/b6a59d88a4a81be783a6c11ada3e58ad16243fcc) .
Could you please review this PR?
Thanks!

[5.0.3] EN-2191-503-frame-widget-labels-fix

---

plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/dynamic-form.js

Hey @joewhite101 ,
pam data table task list confirm button fix.
Could you please have a look.
Thanks!

pam data table task list confirm button fix

---

plugins/entando-plugin-jpdigital-exchange/src/main/java/org/entando/entando/web/digitalexchange/install/DigitalExchangeInstallResource.java
plugins/entando-plugin-jpdigital-exchange/src/test/java/org/entando/entando/web/digitalexchange/install/DigitalExchangeInstallResourceIntegrationTest.java

Changes the HTTP method for the installation of a component from GET to POST

Updates the installation method to POST

---

plugins/entando-plugin-jpdigital-exchange/src/main/java/org/entando/entando/web/digitalexchange/component/DigitalExchangeComponent.java

Just a small change to help with Digital Exchange tests

EN-2313 Added equals/hashcode/toString to help with tests

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/ICaseManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieVersionTransformer.java
plugins/entando-plugin-jpkiebpm/src/main/resources/api/plugins/jpkiebpm/aps/apiMethods.xml
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/dynamic-form.js

Hi @joewhite101,
I did the improvements below on the task list widget:
- Read only Task data fields added to the "Complete" dialog of the task list widget
- Diagram button Javascript fix
- Table Row click fix (open the task detail dialog)
- Refresh of the table of the task list after the confirmation of the form
- Javascript code refactoring
Thanks!

EN-2370-503-PAM-Datatable-task-list-widget-improvements

---

plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/custom-data-table.js

Hey @joewhite101 ,
The Table row onClick event now open a new page that show the new react task detail widget.
Thanks!

EN-2381-503-PAM-process-task-detail-widget

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmCaseInstanceCommentsAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieEndpointDictionary.java
plugins/entando-plugin-jpkiebpm/src/main/resources/sql/plugins/jpkiebpm/port_data_production.sql
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/internalservlet/bpm-case-comments.jsp

The Case comment widget now works also with the taskId parameter.
Thanks!

EN-2384-503-Case-comments-widget-taskId

---

plugins/entando-plugin-jpdigital-exchange/src/main/java/org/entando/entando/aps/system/services/digitalexchange/rating/DERatingsSummary.java
plugins/entando-plugin-jpdigital-exchange/src/main/java/org/entando/entando/web/digitalexchange/rating/DEComponentRatingRequest.java

Added a couple of classes to work with DE instances

En 2313 de rating

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/ICaseManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieVersionTransformer.java
plugins/entando-plugin-jpkiebpm/src/main/resources/api/plugins/jpkiebpm/aps/apiMethods.xml
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/dynamic-form.js

this is the cherry-pick from the 5.0.3 PR below:
1. [EN-2370-503-PAM-Datatable-task-list-widget-improvements 
](https://github.com/entando/entando-components/pull/457)
2. [pam data table task list confirm button fix](https://github.com/entando/entando-components/pull/451) 
Could you please have a look at this PR?
Thanks!

EN-2370-PAM-Datatable-task-list-widget-improvements

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmTypeTaskFormAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/bpmForm.xml
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/KieBpmService.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieVersionTransformer.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmTaskFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/DataUXBuilder.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/dataModels/InputField.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/dataModels/Model.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/specialWidget.xml
plugins/entando-plugin-jpkiebpm/src/main/resources/spring/plugins/jpkiebpm/aps/frontActionsDefs.xml
plugins/entando-plugin-jpkiebpm/src/main/resources/spring/plugins/jpkiebpm/apsadmin/jpkiebpmActionsDefs.xml
plugins/entando-plugin-jpkiebpm/src/main/resources/sql/plugins/jpkiebpm/port_data_production.sql
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/FieldReadOnly.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldCheckBox.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldDatePicker.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldListBox.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldMultipleSelector.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldRadioGroup.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldTextArea.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldTextBox.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/ModelHeader.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/PageModel.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/Section.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/Submit.ftl
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatype-task-form.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jpkiebpm-tiles.xml
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/portal/specialwidget/bpmTaskFormConfig.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/css/entando-kie-form-plugin.css

Hi @joewhite101 
New Task Form Widget added to the PAM plugin.
Thanks!

[5.0.3] EN-2386-503-PAM-show-the-task-form-in-a-new-page

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/KieBpmSystemConstants.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/global-messages_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/global-messages_it.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmDatatableWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmTaskListDatatableWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/tld/plugins/jpkiebpm/bpm.tld
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-task-list.jsp
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/apsadmin/jsp/portal/specialwidget/bpmTaskListDatatableConfig.jsp

New Config fields added.
Thanks!

[5.0.3] EN-2399-503-datatable-task-list-new-configuration-fields 

---

plugins/entando-plugin-jpdigital-exchange/src/test/java/org/entando/entando/aps/system/services/digitalexchange/component/DigitalExchangeComponentsServiceTest.java
plugins/entando-plugin-jpdigital-exchange/src/test/java/org/entando/entando/aps/system/services/pagemodel/DigitalExchangePageModelServiceTest.java

EN-2378 Changes for filtering with OR condition

---

plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-task-details.jsp

this is a fix for the new react task details widget.
Could you please merge this PR?
Thanks!

[5.0.3] EN-2406-503-PAM-add-task-details-widget-to-kie-plugin-2

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/resources/api/plugins/jpkiebpm/aps/apiMethods.xml

this is the cherry-pick from [this PR](https://github.com/entando/entando-components/pull/477).
Thanks!

Add-claim-task-master

---

ui-bundles/misc/entando-misc-inspinia/src/main/webapp/resources/static/js/inspinia.js
ui-bundles/themes/entando-page-inspinia/src/main/resources/sql/bundles/entando-page-inspinia/port_data_production.sql

Hi @joewhite101 @nicpuddu ,
this is a fix for the inspinia BPM bundle.
The metisMenu was not working and we had errors in the browser console so I decided to disable it.
I also commented the demo tooltips that are generating errors.
Thanks!

EN-2415 BPM inspinia js fix

---

plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/pamSeven/TestPamQueryFormResult.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/TestDataUXBuilder.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/apsadmin/util/KieClientTester.java
plugins/src/test/config/conf/contextTestParams.properties
plugins/src/test/resources/log4j2.xml

This PR needs merge of https://github.com/entando/entando-core/pull/792

N-2422 Fix bug on Logger

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/contentAttribute.xml
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/attribute/action/resource/ExtendedResourceAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/MultipleResourceAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceFileChunksStopUploadAndDeleteAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceFileChunksUploadAction.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/resource.xml
plugins/entando-plugin-jacms/src/main/resources/spring/plugins/jacms/apsadmin/resource/resourceActionsConfig.xml
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/resource/resource.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/attachArchive.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/entryResource.jsp
plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/resource/imageArchive.jsp
plugins/entando-plugin-jacms/src/main/webapp/resources/administration/crop-editor/crop-editor.css
plugins/entando-plugin-jacms/src/main/webapp/resources/administration/crop-editor/crop-editor.js
plugins/entando-plugin-jacms/src/main/webapp/resources/administration/file-uploader/file-uploader.js
plugins/entando-plugin-jacms/src/main/webapp/resources/administration/file-uploader/file-uploader.sample.js
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/AllTests.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/apsadmin/resource/TestMultipleResourceAction.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/apsadmin/resource/TestResourceFileChunkUploadAction.java

This PR should be merged together with: https://github.com/entando/entando-core/pull/798

En 2328 en 2327 large file upload

---

plugins/entando-plugin-jacms/src/main/webapp/resources/administration/file-uploader/file-uploader.js

- EN-2327 - fixing cropper null error causing by non ready canvas regenerated on every tab shown.

EN-2327 - fixing cropper

---

plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmTypeTaskFormAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/bpmForm.xml
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/KieBpmService.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/api/ApiTaskInterface.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/KieFormManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/BpmToFormHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/FormToBpmHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/JsonHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/KieProcessFormField.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/DataUXBuilder.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/dataModels/MultipleSubFormField.java
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/FieldDisabled.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/FieldReadOnly.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldCheckBox.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldDatePicker.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/InputFieldTextArea.ftl
plugins/entando-plugin-jpkiebpm/src/main/resources/templates/Section.ftl
plugins/entando-plugin-jpkiebpm/src/main/webapp/resources/plugins/jpkiebpm/static/js/dynamic-form.js
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/MortgageDemoTest.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/TestFormToBpmHelper.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/helper/TestJsonHelper.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/pamSeven/TestPamQueryFormResult.java
plugins/entando-plugin-jpkiebpm/src/test/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/helper/TestDataUXBuilder.java

Hi @joewhite101,
this is a cumulative PR for the tasks listed below:
EN-2464 Form to BPM Payload generation Refactoring
EN-2387 PAM CheckBox Task visualization problem 
EN-2470 PAM Fix Date Fields in forms
Thanks!

EN-2464 EN-2387 EN-2470

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/api/IKieApiManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/api/KieApiManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/KieProcess.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmProcessDatatableWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmSourceAndProcessSelector.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmSourceAndProcessSelectorHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmTaskFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-process-list.jsp

this is the fix for the process list
Thanks!

EN-2319 PAM process list widget fix

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmProcessDiagramAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/api/IKieApiManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/api/KieApiManager.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/system/services/kie/model/KieProcess.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmProcessDatatableWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmSourceAndProcessSelector.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmSourceAndProcessSelectorHelper.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/apsadmin/portal/specialwidget/BpmTaskFormWidgetAction.java
plugins/entando-plugin-jpkiebpm/src/main/webapp/WEB-INF/plugins/jpkiebpm/aps/jsp/widgets/bpm-datatable-process-list.jsp

this is the commits cherry pick from [this PR](https://github.com/entando/entando-components/pull/508)
Thanks!

[5.1.1] EN-2319 PAM process list widget fix

---

plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/BpmTypeFormAction.java
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/package_en.properties
plugins/entando-plugin-jpkiebpm/src/main/java/org/entando/entando/plugins/jpkiebpm/aps/internalservlet/package_it.properties

new task id message fix added.
Thanks!

EN-2471 PAM show new task id after submit in the Form by datatype widget

---

plugins/entando-plugin-jacms/pom.xml
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/contentsettings/ContentSettingsService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsController.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/ContentSettingsCropRatioRequest.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/ContentSettingsDto.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/ContentSettingsEditorRequest.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/ContentSettingsMetadataRequest.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/LastReloadInfoDto.java
plugins/entando-plugin-jacms/src/main/resources/spring/plugins/jacms/aps/cms-servicesConfig.xml
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsControllerIntegrationTest.java

Adds the endpoint for retrieving and editing ContentSettings.

EN6 53 - CMS ContentSettings API Endpoint

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/model/AssetDto.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/model/FileAssetDto.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/model/ImageAssetDto.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java

type parameter is now optional

EN6-128 Digital Assets LIST API endpoint listing all resources

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/AttachAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/CmsHypertextAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/ImageAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/LinkAttribute.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceIntegrationTest.java

This PR depends on the `entando-core` PR: https://github.com/entando/entando-core/pull/819

EN6-131 Content Type Attribute searchable

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/IContentService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/content/ContentController.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/content/validator/BatchContentStatusRequest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java

Creating new endpoint for batch publishing and unpublishing

EN6-140 batch publish

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/content/ContentController.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java

Normalized filters names to match FE expectations, now its possible to filter usings "id" and "description"

EN6-138 Normalizing attributes names to match FE expectations

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/content/ContentController.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java

Normalized columns named received by the frontend to match the DB

EN6-142 Fixing sort names to match frontend expectations

---

plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_maingroup.json
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java

I was investigating a problem with the new restriction field. I ended up not finding anything, but since I created more tests to investigate it I'm pushing them.

EN6-141 Adding more tests

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/AttachAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/CmsHypertextAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/ImageAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/LinkAttribute.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java

Due to new requirements the value for searchableOptionSupported and indexableOptionSupported needed to be changed to some attributes. This build will only work after this PR is ready:
https://github.com/entando/entando-core/pull/838

EN6-143 Changing attributes to match the new requirements

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/IResourceManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java

Adding new endpoint that clone resources
/plugins/cms/assets/{resourceId}/clone

EN6-206 Implementing clone resource endpoint

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid_with_some_links.json
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_some_more_links.json
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_without_link.json
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_without_links.json
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java

There was a problem that when users tried to remove an attribute from a content the attributes would remain

ENG-169 Removing attributes

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/PublicContentSearcherDAO.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestContentManager.java

Fix bug on paginated public content search

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceInterface.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java

This reverts commit 68788d7fafb1b226f9154d1f71e7e10679f55eea.

Revert "ENG-128 Returning unprotected url if user has permission (#608)"

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelValidator.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java

Hi @joewhite101 @Kerruba ,
added a new validation before delete a content template to check if this is used as default in content types.
Thanks

ENG-468: delete content template validation added

---

plugins/entando-plugin-jacms/pom.xml
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerWidgetsIntegrationTest.java

This reverts commit 6d70b224ceb7a381b85dd4a540d7d69d346442b8.

ENG-442 Revert "ENG-442 update tests for csrf enable in spring security (#637)"

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/cache/CmsCacheWrapperManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/IContentManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/AttachAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/CmsHypertextAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/ImageAttribute.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/LinkAttribute.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestContentManager.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceIntegrationTest.java
plugins/entando-plugin-jpgeoref/src/main/java/com/agiletec/plugins/jpgeoref/aps/system/services/content/model/attribute/CoordsAttribute.java

This pr needs merge of PR https://github.com/entando/entando-core/pull/907

ENG-641: Filter of Contents by Boolean attributes (v5.3.0)

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/cache/CmsCacheWrapperManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentManager.java
plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/IContentManager.java
plugins/entando-plugin-jacms/src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestContentManager.java

This pr needs merge of PR  https://github.com/entando/entando-core/pull/906

ENG-641: Improvement of integration tests for searchable attributes

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/services/contentsversioning/ContentVersioningService.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/ContentVersioningController.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/IContentVersioning.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/model/ContentVersionDTO.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/validator/ContentVersioningValidator.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/validator/ContentVersioningValidatorErrorCodes.java
plugins/entando-plugin-jpversioning/src/main/resources/spring/plugins/jpversioning/aps/versioningManagersConfig.xml
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/AllTests.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/services/contentversioning/ContentVersioningServiceTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/ContentVersioningControllerTest.java
ui-bundles/app-views/entando-app-view-cms-default/pom.xml

Hey @joewhite101 @Kerruba @eugeniosant @BrenoQVDS ,
I added the new Rest Controller for the jpversioning plugin. 
I also added the API to list all versions of a content.
Could you please review this PR ?
Thanks

ENG-640: added new Rest Controller and list content versions API

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/services/contentsversioning/ContentVersioningService.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/ContentVersioningController.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/IContentVersioning.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/validator/ContentVersioningValidator.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/validator/ContentVersioningValidatorErrorCodes.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/services/contentversioning/ContentVersioningServiceTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/ContentVersioningControllerTest.java

Hi @BrenoQVDS @eugeniosant @Kerruba @gidesan  ,
added get content version details API and get content version list optimization
Thanks

ENG-640: add get content version details API

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/services/contentsversioning/ContentVersioningService.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/ContentVersioningController.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/contentsversioning/IContentVersioning.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/services/contentversioning/ContentVersioningServiceTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/ContentVersioningControllerIntegrationTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/ContentVersioningControllerTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/json/1_PUT_content_with_boolean_attribute.json
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/contentversioning/json/2_PUT_content_with_boolean_attribute.json
plugins/entando-plugin-jpversioning/src/test/resources/xml/content_test.xml

Hey @BrenoQVDS @eugeniosant @gidesan ,
I added a new API to recover a specific content version from versioning history.
Could you please check this PR ?
Thanks

ENG-635: recover content version API added

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/services/configuration/VersioningConfigurationService.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/configuration/IVersioningConfiguration.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/configuration/VersioningConfigurationController.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/services/configuration/VersioningConfigurationServiceTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/configuration/VersioningConfigurationControllerIntegrationTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/configuration/VersioningConfigurationControllerTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/configuration/json/1_PUT_versioning_configuration.json
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/content/ContentVersioningControllerIntegrationTest.java

Hey @BrenoQVDS @eugeniosant @gidesan ,
new PUT versioning configuration API added.
Thanks

ENG-652: put versioning configuration api added

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/services/content/ContentVersioningService.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/content/ContentVersioningController.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/content/IContentVersioning.java
plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/content/validator/ContentVersioningValidator.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/content/ContentVersioningControllerIntegrationTest.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/content/ContentVersioningControllerTest.java

Hey @BrenoQVDS @eugeniosant @gidesan ,
delete versioning configuration api added.
Thanks

ENG-737: delete versioning configuration api added

---

plugins/entando-plugin-jacms/src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java

Reverts entando/entando-components#674

Revert "ENG-640: content dates format fix"

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/content/model/ContentVersionDTO.java

Hi @BrenoQVDS @w-caffiero-entando @gidesan ,
Could you please review this PR?
Thanks

ENG-640: Content Version date format fix

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelReferencesRequestListProcessor.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/model/ContentModelReferenceDTO.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelReferencesValidator.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerUnitTest.java

Hey @BrenoQVDS @Kerruba @gidesan @eugeniosant ,
content model references api redesigned.
Thanks

ENG-470: content model references api redesign

---

plugins/entando-plugin-jpversioning/src/main/java/org/entando/entando/plugins/jpversioning/web/resource/IResourceVersioning.java
plugins/entando-plugin-jpversioning/src/test/java/org/entando/entando/jpversioning/web/resource/ResourceVersioningControllerIntegrationTest.java

Changing from CONTENT_EDITOR to MANAGE_RESOURCES

ENG-738 Changing permissions

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java

Hi @BrenoQVDS @Kerruba @gidesan ,
new content template usage count api added.
Could you please review this PR ?
Thanks

ENG-470: content template usage count api added

---

plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_contentFinding.jsp

ENG-731-amend-dataTable in order to remove filtering

ENG-731: amend-dataTable in order to remove filtering

---

plugins/entando-plugin-jacms/src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_contentFinding.jsp

ENG-731: admin-console-cms-amend-datatable

ENG-731: admin-console-cms-amend-datatable

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelService.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelUsageDetailsRequestListProcessor.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelUsageDetailsValidator.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerUnitTest.java

Hi @BrenoQVDS @Kerruba @gidesan ,
new content template usage details api added.
Thanks

ENG-546: content template usage details api added

---

plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java
plugins/entando-plugin-jacms/src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerWidgetsIntegrationTest.java

Added test coverage with appropriate permissions to page configuration with cms widgets

ENG-683 Page Configuration Permissions

---

plugins/entando-plugin-jacms/src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java

Hey @BrenoQVDS ,
This is a typo fix.
could you please merge this PR?
Thanks

ENG-842 typo fix

---

ui-bundles/app-views/entando-app-view-cms-default/pom.xml

Hi @BrenoQVDS @eugeniosant @Kerruba @gidesan @w-caffiero-entando ,
Seo plugin and entando.version variable added to the pom.xml file.
Thanks

ENG-773 seo plugin added
